### ISSUE TITLE
name 'xrange' is not defined

### ISSUE THREAD

**Issue by subhampro** [BitTheByte/YouTubeShop#39] opened 2019-12-17 09:48 UTC
DevTools listening on ws://127.0.0.1:57376/devtools/browser/8dbed15e-aefb-45c5-86fc-e5b71a26c881
Traceback (most recent call last):
  File "C:\Users\prosu\Downloads\YouTubeShop-master\yt.py", line 96, in <module>
    threader.put(subscribe_wrapper,[credentials[0],credentials[1],identifier])
  File "C:\Users\prosu\Downloads\YouTubeShop-master\lib\multi.py", line 43, in put
    for _ in xrange(self.q.qsize()): self.__t()
NameError: name 'xrange' is not defined

**Comment by BitTheByte** [comment] 2019-12-17 09:55
Please use Python 2 as xrange is renamed to range in Python 3

**Comment by subhampro** [comment] 2019-12-17 14:25
i am not able to find a stable ver of Python 2.0 ! can you share link ?

**Comment by BitTheByte** [comment] 2019-12-17 20:01
Download the **latest** Python 2 version from the official website https://python.org

**Comment by BitTheByte** [comment] 2020-01-03 08:19
I'm closing this for now, feel free to reopen if the issue continues.

**Closed by BitTheByte** 2020-01-03 08:19 UTC

**Comment by ghost** [comment] 2021-08-03 17:47
The problem is still exists even on python2

**Comment by ghost** [comment] 2021-08-03 17:49
> The problem is still exists even on python2

![image](https://user-images.githubusercontent.com/87362984/128062349-8d447d99-fedc-48c3-9465-c7879fc832a7.png)
